### ISSUE TITLE
Provide a font pls

### ISSUE THREAD

**Issue by Xiscollado** [sschoger/heroicons-ui#5]
a font would be awesome

**Comment by etdte** [comment]
Hey!
I played a bit with free generator, it's far from perfection, i think, but u may find this one useful, until Steve, or someone else will decide to make font.

[heroicons-ui-font.zip](https://github.com/sschoger/heroicons-ui/files/1746082/heroicons-ui-font.zip)

**Comment by Xiscollado** [comment]
Thanks!
